export enum Constants {
  SKIP = 0,
  LIMIT = 10,
  USER = 'user',
  SUCCESSSTATUSCODE = 200,
  SUCCESSSTATUSCODE1 = 201,
  SUCCESSSTATUSCODE2 = 202,
  SUCCESSSTATUSCODE3 = 203,
  EMAILUNREGISTERED = 'unregister',
  EMAILREGISTERED = 'register',
  EMAILSUBSCRIBED = 'subscribe',
  SESSIONTOKENSTRING = 'token',
  CURLANG = 'curLang',
  ACTIVEEMAIL = 'activeEmail',
  ACTIVEPASSWORD = 'activePassword',
  LOGGEDINUSER = 'user',
  LOGGEDINUSERID = 'userid',
  PHONE = 'phone',
}
